/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabsharingcj;

import hib.dto.EmployeeSignin;
import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author HP
 */
public class ContactWindow extends javax.swing.JFrame {

    /**
     * Creates new form HomeEmployeeWindow
     */
    public ContactWindow() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLab2 = new javax.swing.JLabel();
        jLab6 = new javax.swing.JLabel();
        jLab1 = new javax.swing.JLabel();
        jLab3 = new javax.swing.JLabel();
        jLab4 = new javax.swing.JLabel();
        jLab5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab2.setBackground(new java.awt.Color(255, 255, 255));
        jLab2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_user_25px.png"))); // NOI18N
        jLab2.setText("Profile");
        jLab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLab2MouseClicked(evt);
            }
        });
        jPanel2.add(jLab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 50));

        jLab6.setBackground(new java.awt.Color(255, 255, 255));
        jLab6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout_25px.png"))); // NOI18N
        jLab6.setText("Exit");
        jLab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLab6MouseClicked(evt);
            }
        });
        jPanel2.add(jLab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 140, 50));

        jLab1.setBackground(new java.awt.Color(255, 255, 255));
        jLab1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_25px.png"))); // NOI18N
        jLab1.setText("Home");
        jLab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLab1MouseClicked(evt);
            }
        });
        jPanel2.add(jLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 50));

        jLab3.setBackground(new java.awt.Color(255, 255, 255));
        jLab3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phone_25px.png"))); // NOI18N
        jLab3.setText("Contact");
        jLab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLab3MouseClicked(evt);
            }
        });
        jPanel2.add(jLab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 50));

        jLab4.setBackground(new java.awt.Color(255, 255, 255));
        jLab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form_25px.png"))); // NOI18N
        jLab4.setText("Feedback");
        jLab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLab4MouseClicked(evt);
            }
        });
        jPanel2.add(jLab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, 50));

        jLab5.setBackground(new java.awt.Color(255, 255, 255));
        jLab5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaint_25px.png"))); // NOI18N
        jLab5.setText("Complaint");
        jPanel2.add(jLab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 490));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Get in touch!!");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phone_25px.png"))); // NOI18N
        jLabel3.setText("+91 7898076539");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAB4.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gmail Logo_25px.png"))); // NOI18N
        jLabel5.setText("carsharing@gmail.com");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 660, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab1MouseClicked
    
    }//GEN-LAST:event_jLab1MouseClicked

    private void jLab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab2MouseClicked
     new  ProfileEmployeeWindow().setVisible(true); 
          
         dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLab2MouseClicked

    private void jLab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab3MouseClicked
       new ContactWindow().setVisible(true);
       dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLab3MouseClicked

    private void jLab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab4MouseClicked
         new FeedbackWindow().setVisible(true);
         dispose();
       // TODO add your handling code here:
    }//GEN-LAST:event_jLab4MouseClicked

    private void jLab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab6MouseClicked
         new LoginWindow2().setVisible(true);
         dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLab6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLab1;
    private javax.swing.JLabel jLab2;
    private javax.swing.JLabel jLab3;
    private javax.swing.JLabel jLab4;
    private javax.swing.JLabel jLab5;
    private javax.swing.JLabel jLab6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
